
[[battery.display]]
threshold = 30
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[character]
use_symbol_for_status = true

[php]
symbol = "ğŸ˜ "
style = "bold blue"


[nodejs]
symbol = "ğŸ¤– "
style = "bold green"

[git_branch]
symbol = "ğŸ”¸ "
style = "bold yellow"
